# Network
MODEL_USE: rela
LAYER: 4
HIDDEN_SIZE: 1024
FF_SIZE: 4096
MULTI_HEAD: 8
DROPOUT_R: 0.1
FLAT_MLP_SIZE: 512
FLAT_GLIMPSES: 1
FLAT_OUT_SIZE: 1024
USE_BBOX_FEAT: True

# Execution
BATCH_SIZE: 128
LR_BASE: 0.00001 # 0.00005 for train+val+vg->test
LR_DECAY_R: 0.2
LR_DECAY_LIST: [10, 15]
WARMUP_EPOCH: 3
MAX_EPOCH: 20
GRAD_NORM_CLIP: -1
GRAD_ACCU_STEPS: 4 # to reduce GPU memory cost
LOSS_FUNC: bce
LOSS_REDUCTION: sum
OPT: Adam
OPT_PARAMS: {betas: '(0.9, 0.98)', eps: '1e-9'}
